Repository aiven/devportal, pull requests merged in 2022-10, with the labels that each got.

#1443 Add logs to Issue message
  .github/ISSUE_TEMPLATE/linkcheck_report.md
  .github/workflows/linkcheck.yaml
Labels: Maintanance

#1455 Updating page title per discussion
  .github/vale/styles/Aiven/capitalization_headings.yml
  docs/tools/terraform/reference/cookbook.rst
Labels: terraform

#1403 Migration article: Issue 808 - Attach VPC to AWS Transit Gateway
  .github/vale/styles/Aiven/capitalization_headings.yml
  _toc.yml
  docs/platform/howto/attach-vpc-aws-tgw.rst
Labels: Networking, migration-task, Platform

#1456 How to create, rename, and delete project
  .github/vale/styles/Aiven/capitalization_headings.yml
  _toc.yml
  docs/platform/howto/manage-project.rst
  docs/tools/cli/project.rst
Labels: migration-task

#1169 Added AWS assume role document
  .github/vale/dicts/aiven.dic
  .github/vale/styles/Aiven/capitalization_headings.yml
  _toc.yml
  docs/products/kafka/kafka-connect/howto/s3-iam-assume-role.rst
  docs/products/kafka/kafka-connect/howto/s3-sink-connector-aiven.rst
Labels: migration-task

#1370 Add a test for missing :alt: in image directives
  .github/vale/styles/Aiven/missing_alt_in_image.yml
  .github/vale/tests/missing_image_alt.rst
  .github/vale/tests/shelltest.test
  docs/platform/howto/create_new_service.rst
  docs/platform/howto/manage-project.rst
  docs/platform/howto/use-aws-privatelinks.rst
  docs/products/grafana.rst
  docs/products/grafana/get-started.rst
  docs/products/grafana/howto/log-in.rst
  docs/products/m3db.rst
  docs/products/m3db/getting-started.rst
  docs/products/postgresql/howto/manage-pool.rst
  docs/products/postgresql/reference/list-of-extensions.rst
Labels: linting

#1458 Migration support center article
  _toc.yml
  docs/platform/howto/project-support-center.rst
Labels: migration-task

#1433 New article for using dsbulk with cassandra
  .github/vale/dicts/aiven.dic
  _toc.yml
  docs/products/cassandra/howto/use-dsbulk-with-cassandra.rst
  docs/products/cassandra/howto/use-nosqlbench-with-cassandra.rst
Labels: cassandra

#1492 A subset of Vale warning fixes
  .github/vale/dicts/aiven.dic
  docs/tools/cli/service.rst
  docs/tools/cli/vpc.rst
  docs/tools/kubernetes.rst
  docs/tools/terraform/concepts/data-sources.rst
  docs/tools/terraform/howto/config-postgresql-provider.rst
  docs/tools/terraform/howto/upgrade-provider-v1-v2.rst
  docs/tools/terraform/howto/upgrade-to-opensearch.rst
  docs/tools/terraform/reference/cookbook/kafka-debezium-postgres-source.rst
Labels: Maintanance

#1453 Migrate availability zones article [DOC-18]
  .github/vale/dicts/aiven.dic
  .github/vale/styles/Aiven/capitalization_headings.yml
  _toc.yml
  docs/platform/concepts.rst
  docs/platform/concepts/availability-zones.rst
Labels: migration-task

#1368 Add a new rule to check for markdown-style links
  .github/vale/styles/Aiven/markdown_links.yml
  .github/vale/tests/markdown_links.rst
  .github/vale/tests/shelltest.test
Labels: linting

#1396 Mysql replication
  _toc.yml
  docs/products/mysql/concepts/mysql-replication.rst
  docs/products/mysql/howto/create-missing-primary-keys.rst
  docs/products/mysql/howto/create-tables-without-primary-keys.rst
Labels: mysql

#1484 migrate azure vnet peering article
  _toc.yml
  docs/platform/howto/manage-vpc-peering.rst
  docs/platform/howto/vnet-peering-azure.rst
Labels: migration-task

#1292 Fix #1076 Migrate article: Preparing for high load Fix #1076
  _toc.yml
  docs/platform/howto/prepare-for-high-load.rst
Labels: migration-task

#1487 AWS VPC peering article
  _toc.yml
  docs/platform/howto/manage-vpc-peering.rst
  docs/platform/howto/vpc-peering-aws.rst
  docs/platform/howto/vpc-peering-gcp.rst
Labels: migration-task

#1509 Fix broken links
  docs/products/clickhouse/howto/use-cli.rst
  docs/products/opensearch/howto/opensearch-search-and-python.rst
Labels: Maintanance
